In [2]:
from bs4 import BeautifulSoup
import pandas as pd

In [15]:

for i in ['Singles','Doubles','Mixed']:
    for j in ['2.5','3.0','3.5','4.0','4.5','5.0','5.5','6.0']:
        print('hello {} {}'.format(i,j)) 


        soup = BeautifulSoup(open(r"C:\Tim\pickleball\new ratings system\extracting data from 30 sept pull\USAPA Pickleball {} {}.html".format(i,j)), "html.parser")

        my_rows = soup.find("table").find_all('tr')

        data = [[td.findChildren(text=True) for td in tr.findAll("td")] for tr in my_rows]

        headers = [[td.findChildren(text=True) for td in tr.findAll("th")] for tr in my_rows]

        headers_list = headers[0][1:14]

        just_the_headers = [a[0] for a in headers_list]

        df = pd.DataFrame(data)

        df = df.applymap(lambda x: x if not isinstance(x, list) else x[0] if len(x) else '')

        df = df.drop(columns=0)

        df.columns = just_the_headers

        df = df.drop(0)

        df.to_csv(r"C:\Tim\pickleball\new ratings system\extracting data from 30 sept pull\USAPA Pickleball {} {}.csv".format(i,j))

hello Singles 2.5
hello Singles 3.0
hello Singles 3.5
hello Singles 4.0
hello Singles 4.5
hello Singles 5.0
hello Singles 5.5
hello Singles 6.0
hello Doubles 2.5
hello Doubles 3.0
hello Doubles 3.5
hello Doubles 4.0
hello Doubles 4.5
hello Doubles 5.0
hello Doubles 5.5
hello Doubles 6.0
hello Mixed 2.5
hello Mixed 3.0
hello Mixed 3.5
hello Mixed 4.0
hello Mixed 4.5
hello Mixed 5.0
hello Mixed 5.5
hello Mixed 6.0

In [ ]:
for i in ['Singles','Doubles','Mixed']:
    for j in ['2.5','3.0','3.5','4.0','4.5','5.0','5.5','6.0']
    print('hello {}')

In [9]:
for i in ['Singles','Doubles','Mixed']:
    for j in ['2.5','3.0','3.5','4.0','4.5','5.0','5.5','6.0']:
        print('hello {}'.format(j))

hello 2.5
hello 3.0
hello 3.5
hello 4.0
hello 4.5
hello 5.0
hello 5.5
hello 6.0
hello 2.5
hello 3.0
hello 3.5
hello 4.0
hello 4.5
hello 5.0
hello 5.5
hello 6.0
hello 2.5
hello 3.0
hello 3.5
hello 4.0
hello 4.5
hello 5.0
hello 5.5
hello 6.0

In [14]:
for i in ['Singles','Doubles','Mixed']:
    for j in ['2.5','3.0','3.5','4.0','4.5','5.0','5.5','6.0']:
        print('hello {} {}'.format(i,j))

hello Singles 2.5
hello Singles 3.0
hello Singles 3.5
hello Singles 4.0
hello Singles 4.5
hello Singles 5.0
hello Singles 5.5
hello Singles 6.0
hello Doubles 2.5
hello Doubles 3.0
hello Doubles 3.5
hello Doubles 4.0
hello Doubles 4.5
hello Doubles 5.0
hello Doubles 5.5
hello Doubles 6.0
hello Mixed 2.5
hello Mixed 3.0
hello Mixed 3.5
hello Mixed 4.0
hello Mixed 4.5
hello Mixed 5.0
hello Mixed 5.5
hello Mixed 6.0

In [6]:
levels = ['2.5','3.0','3.5','4.0','4.5','5.0','5.5','6.0']
divisions = ['Singles','Doubles','Mixed']

In [10]:
files = ['USAPA Pickleball {} {}.csv'.format(i,j) for i in divisions for j in levels ]

In [11]:
files

['USAPA Pickleball Singles 2.5.csv',
 'USAPA Pickleball Singles 3.0.csv',
 'USAPA Pickleball Singles 3.5.csv',
 'USAPA Pickleball Singles 4.0.csv',
 'USAPA Pickleball Singles 4.5.csv',
 'USAPA Pickleball Singles 5.0.csv',
 'USAPA Pickleball Singles 5.5.csv',
 'USAPA Pickleball Singles 6.0.csv',
 'USAPA Pickleball Doubles 2.5.csv',
 'USAPA Pickleball Doubles 3.0.csv',
 'USAPA Pickleball Doubles 3.5.csv',
 'USAPA Pickleball Doubles 4.0.csv',
 'USAPA Pickleball Doubles 4.5.csv',
 'USAPA Pickleball Doubles 5.0.csv',
 'USAPA Pickleball Doubles 5.5.csv',
 'USAPA Pickleball Doubles 6.0.csv',
 'USAPA Pickleball Mixed 2.5.csv',
 'USAPA Pickleball Mixed 3.0.csv',
 'USAPA Pickleball Mixed 3.5.csv',
 'USAPA Pickleball Mixed 4.0.csv',
 'USAPA Pickleball Mixed 4.5.csv',
 'USAPA Pickleball Mixed 5.0.csv',
 'USAPA Pickleball Mixed 5.5.csv',
 'USAPA Pickleball Mixed 6.0.csv']

In [42]:

result = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

In [43]:
result

,Unnamed: 0,Last Name,First Name,Middle,M/W,Doubles,Mixed,Singles,Legacy-Dbl,Legacy-Sgl,City,State,
0,1,Alexander,David,NaN,M,3.5,3.5,2.5,NaN,NaN,Layton,UT,contact
1,2,Ambrose,David,Montague,M,3.0,3.0,2.5,NaN,NaN,South Portland,ME,contact
2,3,Anderson,Sherry,NaN,F,2.5,3.0,2.5,2.5,NaN,Alto,NM,contact
3,4,Aull,Chiqui,M,F,3.5,3.5,2.5,3,NaN,West Chester,OH,contact
4,5,Bacon,Dennis,NaN,M,3.0,3.5,2.5,3.5,NaN,Moultonboro,NH,contact
5,6,Bamberger,Audrey,NaN,F,4.0,3.5,2.5,3.5,3,Naples,FL,contact
6,7,Barnson,Brook,NaN,M,3.5,3.5,2.5,3.5,NaN,West Jordan,UT,contact
7,8,Baughn,Wanda,S,F,3.0,3.0,2.5,3,NaN,Harher Heights,TX,contact
8,9,Becenti,Priscilla,NaN,F,3.0,NaN,2.5,3,NaN,Rehoboth,NM,contact
9,10,Benard,David,NaN,M,2.5,2.5,2.5,NaN,NaN,Galveston,TX,contact
10,11,Bjorklund,Olivia,E,F,NaN,3.0,2.5,NaN,NaN,Ferndale,WA,contact
11,12,Blumerick,Marika,L.,F,3.5,3.5,2.5,3.5,NaN,Shelby Twp,MI,contact
12,13,Bobbitt,Michael,Taylor,M,NaN,NaN,2.5,NaN,NaN,Rowlett,TX,contact
13,14,Boeer,Kathy,NaN,F,3.0,3.0,2.5,3,NaN,Brenham,TX,contact
14,15,Bowman,Janet,NaN,F,4.0,3.5,2.5,3.5,3.5,Phenix City,AL,contact
15,16,Bowness,Dennis,Allan,M,3.5,3.5,2.5,3.5,0,Red Deer,AB,contact
16,17,Braun,Carol,J,F,4.0,3.5,2.5,3.5,NaN,Peachtree City,GA,contact
17,18,BROWN,REGINALD,NaN,M,3.0,NaN,2.5,3,NaN,Stockbridge,GA,contact
18,19,Buchman,Susan,NaN,F,2.5,2.5,2.5,3,NaN,Pittsburgh,PA,contact
19,20,Burch,Gene,NaN,M,3.0,3.0,2.5,3,NaN,Jewitt City,CT,contact
20,21,Burke,Tom,NaN,M,3.5,3.5,2.5,3,NaN,shoreline,WA,contact
21,22,Cameron,Elizabeth,M,F,3.5,3.5,2.5,3.5,NaN,Park Ridge,IL,contact
22,23,Cardenaz,Steven,Casey,M,NaN,3.0,2.5,NaN,NaN,Ogden,UT,contact
23,24,Caron,Linda,NaN,F,3.0,3.5,2.5,3,NaN,Denton,TX,contact
24,25,Carter,Andy,NaN,M,3.5,3.0,2.5,3,NaN,Lubbock,TX,contact
25,26,Chan,Spencer,G,M,3.0,NaN,2.5,NaN,NaN,San Francisco,CA,contact
26,27,Chaves,Marisa,NaN,F,3.5,3.0,2.5,3,NaN,Rehoboth Beach,DE,contact
27,28,Clark,Leo,NaN,M,3.0,3.5,2.5,3,NaN,Galveston,TX,contact
28,29,Click,Gene,NaN,M,4.0,3.5,2.5,3.5,NaN,Oklahoma City,OK,contact
29,30,Click,Katelyn,NaN,F,3.5,3.0,2.5,3,NaN,Oklahoma City,OK,contact
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33480,111,Toureilles,Daniel,R,M,5.0,5.5,4.5,5,0,Houston,TX,contact
33481,112,Valenti,Joe,NaN,M,4.5,5.5,4.5,5,0,Rochester,NY,contact
33482,113,Vavra,Dalton,NaN,M,5.5,5.5,5.5,5,0,Gig Harbor,WA,contact
33483,114,Wage,David,A,M,5.5,5.5,4.5,5,0,Fresno,CA,contact
33484,115,Warnick,Jeffrey,NaN,M,6.0,5.5,4.5,4.5,0,Pasadena,CA,contact
33485,116,Waters,Leigh,NaN,F,5.5,5.5,4.5,5,5,Village of Golf,FL,contact
33486,117,Weinbach,Dave,S,M,6.0,5.5,5.0,5,0,Madison,WI,contact
33487,118,Welsher,Eva,M,F,5.0,5.5,NaN,4.5,NaN,grosse pointe farms,MI,contact
33488,119,Whitehouse,Sylvia,NaN,F,5.0,5.5,NaN,5,0,Palm Coast,FL,contact
33489,120,wilhelm,helen,NaN,F,5.5,5.5,NaN,5,NaN,coppell,TX,contact
33490,121,Wilkins,Melinda,NaN,F,5.5,5.5,NaN,5,NaN,St. George,UT,contact
33491,122,Williams,Bonnie,B,F,5.5,5.5,5.0,5,5,Portland,OR,contact
33492,123,Williams,Kara,Lee,F,5.0,5.5,4.5,5,NaN,Carlsbad,CA,contact
33493,124,Williams,Nicklaus,B,M,5.5,5.5,5.0,5,0,Seattle,WA,contact
33494,125,Witsken,Rick,NaN,M,5.5,5.5,5.0,5,0,Zionsville,IN,contact
33495,126,Wren,Tyler,J,M,5.5,5.5,5.0,5,0,Fruit Heights,UT,contact
33496,127,Zbinden Jr,Randel,NaN,M,6.0,5.5,NaN,5,0,St. George,UT,contact
33497,128,Zilkha,Daniel,M,M,5.0,5.5,4.5,5,0,Houston,TX,contact
33498,1,Anderson,Kirsten,NaN,F,6.0,6.0,NaN,5,0,Newport Beach,CA,contact
33499,2,Ansboury,Sarah,NaN,F,6.0,6.0,5.0,5,5,Portland,OR,contact
33500,3,Dawson,Callan,NaN,M,5.5,6.0,NaN,5,0,Carlsbad,CA,contact
33501,4,Jardim,Simone,P,F,6.0,6.0,5.5,5,0,Mason,MI,contact
33502,5,Johns,Benjamin,NaN,M,6.0,6.0,5.5,5,0,Laytonsville,MD,contact
33503,6,Kovalova,Lucia,NaN,F,6.0,6.0,5.5,5,0,Wichita,KS,contact
33504,7,Moore,Daniel,J,M,6.0,6.0,5.5,5,0,Colorado Springs,CO,contact
33505,8,Newman,Lindsey,Marie,F,5.0,6.0,5.0,5,NaN,Queen Creek,AZ,contact
33506,9,Rozpedski,Marcin,NaN,M,6.0,6.0,6.0,5,0,Bermuda Dunes,CA,contact
33507,10,Tereschenko,Irina,NaN,F,6.0,6.0,5.5,5,0,Bellevue,WA,contact
33508,11,Wright,Matthew,D,M,6.0,6.0,5.0,5,0,Wichita,KS,contact
33509,12,Yates,Kyle,NaN,M,6.0,6.0,5.5,5,0,Fort Myers,FL,contact

In [44]:
result = result.drop(result.columns[0],axis=1)

In [33]:
result.to_csv('all divisions combined.csv')

In [45]:
result.shape

(33510, 12)

In [37]:
result.drop_duplicates().shape

(21528, 12)

In [46]:
result = result.drop_duplicates()

In [47]:
result

,Last Name,First Name,Middle,M/W,Doubles,Mixed,Singles,Legacy-Dbl,Legacy-Sgl,City,State,
0,Alexander,David,NaN,M,3.5,3.5,2.5,NaN,NaN,Layton,UT,contact
1,Ambrose,David,Montague,M,3.0,3.0,2.5,NaN,NaN,South Portland,ME,contact
2,Anderson,Sherry,NaN,F,2.5,3.0,2.5,2.5,NaN,Alto,NM,contact
3,Aull,Chiqui,M,F,3.5,3.5,2.5,3,NaN,West Chester,OH,contact
4,Bacon,Dennis,NaN,M,3.0,3.5,2.5,3.5,NaN,Moultonboro,NH,contact
5,Bamberger,Audrey,NaN,F,4.0,3.5,2.5,3.5,3,Naples,FL,contact
6,Barnson,Brook,NaN,M,3.5,3.5,2.5,3.5,NaN,West Jordan,UT,contact
7,Baughn,Wanda,S,F,3.0,3.0,2.5,3,NaN,Harher Heights,TX,contact
8,Becenti,Priscilla,NaN,F,3.0,NaN,2.5,3,NaN,Rehoboth,NM,contact
9,Benard,David,NaN,M,2.5,2.5,2.5,NaN,NaN,Galveston,TX,contact
10,Bjorklund,Olivia,E,F,NaN,3.0,2.5,NaN,NaN,Ferndale,WA,contact
11,Blumerick,Marika,L.,F,3.5,3.5,2.5,3.5,NaN,Shelby Twp,MI,contact
12,Bobbitt,Michael,Taylor,M,NaN,NaN,2.5,NaN,NaN,Rowlett,TX,contact
13,Boeer,Kathy,NaN,F,3.0,3.0,2.5,3,NaN,Brenham,TX,contact
14,Bowman,Janet,NaN,F,4.0,3.5,2.5,3.5,3.5,Phenix City,AL,contact
15,Bowness,Dennis,Allan,M,3.5,3.5,2.5,3.5,0,Red Deer,AB,contact
16,Braun,Carol,J,F,4.0,3.5,2.5,3.5,NaN,Peachtree City,GA,contact
17,BROWN,REGINALD,NaN,M,3.0,NaN,2.5,3,NaN,Stockbridge,GA,contact
18,Buchman,Susan,NaN,F,2.5,2.5,2.5,3,NaN,Pittsburgh,PA,contact
19,Burch,Gene,NaN,M,3.0,3.0,2.5,3,NaN,Jewitt City,CT,contact
20,Burke,Tom,NaN,M,3.5,3.5,2.5,3,NaN,shoreline,WA,contact
21,Cameron,Elizabeth,M,F,3.5,3.5,2.5,3.5,NaN,Park Ridge,IL,contact
22,Cardenaz,Steven,Casey,M,NaN,3.0,2.5,NaN,NaN,Ogden,UT,contact
23,Caron,Linda,NaN,F,3.0,3.5,2.5,3,NaN,Denton,TX,contact
24,Carter,Andy,NaN,M,3.5,3.0,2.5,3,NaN,Lubbock,TX,contact
25,Chan,Spencer,G,M,3.0,NaN,2.5,NaN,NaN,San Francisco,CA,contact
26,Chaves,Marisa,NaN,F,3.5,3.0,2.5,3,NaN,Rehoboth Beach,DE,contact
27,Clark,Leo,NaN,M,3.0,3.5,2.5,3,NaN,Galveston,TX,contact
28,Click,Gene,NaN,M,4.0,3.5,2.5,3.5,NaN,Oklahoma City,OK,contact
29,Click,Katelyn,NaN,F,3.5,3.0,2.5,3,NaN,Oklahoma City,OK,contact
...,...,...,...,...,...,...,...,...,...,...,...,...
32303,Peden,James,NaN,M,3.0,4.5,NaN,3.5,NaN,Andover,MN,contact
32316,Persampieri,Michael,J,M,NaN,4.5,NaN,NaN,NaN,Grand Island,NE,contact
32331,Pickett,Jayme,NaN,F,3.5,4.5,NaN,4,0,St.George,UT,contact
32337,Pittman,Charles,T.,M,3.5,4.5,NaN,4,0,Little Rock,AR,contact
32389,Rathkamp,Donna,S,F,3.5,4.5,NaN,4,0,Cypress,TX,contact
32403,Redding,Kay,NaN,F,3.5,4.5,NaN,4,0,Searcy,AR,contact
32419,Ribble,Karen,NaN,F,3.5,4.5,NaN,4,0,Springfield,TN,contact
32421,Ricciardi,Phillip,K,M,3.5,4.5,NaN,4,0,Pelham,NH,contact
32458,Rodgers,Carrie,S,F,3.0,4.5,3.0,3.5,3,Grand Haven,MI,contact
32567,Seamayer,Kay,NaN,F,3.5,4.5,NaN,3.5,0,De Soto,TX,contact
32576,Shallahamer,Kenneth,K,M,3.5,4.5,NaN,3,0,Costa Mesa,CA,contact
32611,Smart,Yvonne,N,F,NaN,4.5,NaN,NaN,NaN,Columbia,MD,contact
32618,Smith,Jill,M,F,NaN,4.5,NaN,4,0,Sun Prairie,WI,contact
32619,Smith,Judy,Hoyt,F,NaN,4.5,NaN,3.5,NaN,Hilton Head Island,SC,contact
32633,Smith,Scott,D,M,3.5,4.5,NaN,4,0,Sun Prairie,WI,contact
32636,Smithgall,Sonya,C,F,3.0,4.5,NaN,3,0,Moses Lake,WA,contact
32653,Spencer,Nancy,S,F,NaN,4.5,NaN,3.5,NaN,Griffin,GA,contact
32672,Stautz,Al,NaN,M,NaN,4.5,NaN,4,0,Vancouver,WA,contact
32683,Stingley,Brett,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32874,Garrido,Wendy,W.,F,NaN,5.0,NaN,5,0,Grass Valley,CA,contact
32883,Gibbs,Ronald,D,M,NaN,5.0,NaN,5,0,Livingston,TX,contact
32900,Grubbs,Amy,NaN,F,3.5,5.0,NaN,3.5,0,Fort Wayne,IN,contact
33039,little,caroline,clark,F,3.0,5.0,NaN,4,NaN,huntsville,AL,contact
33138,Osterman,Samantha,N,F,NaN,5.0,NaN,NaN,NaN,San Pedro,CA,contact
33163,Peterson,Paula,J,F,3.5,5.0,NaN,4.5,0,Redmond,WA,contact
33230,Scott,Cheryle,B,F,NaN,5.0,NaN,NaN,NaN,Cherry Hill,NJ,contact
33239,Sidelmann,Leah,A,F,NaN,5.0,NaN,NaN,NaN,NORTH VANCOUVER,BC,contact
33287,Tandy,Sheri,NaN,F,3.5,5.0,NaN,3.5,0,Gig Harbor,WA,contact
33344,Williams,Clifton,NaN,M,4.0,5.0,NaN,4.5,NaN,Ann Arbor,MI,contact
33427,Klaic,Darija,NaN,F,NaN,5.5,NaN,4,NaN,Austin,TX,contact

In [48]:
result.to_csv('all divisions combined.csv')

In [3]:
test = pd.read_csv('USAPA Pickleball Mixed 4.0.csv')

In [4]:
test

,Unnamed: 0,Last Name,First Name,Middle,M/W,Doubles,Mixed,Singles,Legacy-Dbl,Legacy-Sgl,City,State,
0,1,Aaron,Paul,NaN,M,4.0,4,NaN,4.0,NaN,Hendersonville,NC,contact
1,2,Abar,Gordon,NaN,M,3.5,4,NaN,4.0,1.0,Mesa,AZ,contact
2,3,Abbott,Deke,C,M,3.5,4,NaN,NaN,NaN,Troy,NC,contact
3,4,abrahams,matthew,NaN,M,4.0,4,NaN,4.0,NaN,Centennial,CO,contact
4,5,Abston,John,R,M,4.0,4,NaN,3.5,0.0,Strongsville,OH,contact
5,6,Acker,Carol,A,F,4.0,4,NaN,4.0,0.0,Anthem,AZ,contact
6,7,Ackerman,Joanne,L,F,NaN,4,NaN,3.5,0.0,Phoenix,AZ,contact
7,8,Acord,Karen,S,F,4.0,4,NaN,3.5,NaN,Lutz,FL,contact
8,9,Acord,Randall,D,M,3.5,4,NaN,3.5,NaN,Lutz,FL,contact
9,10,Adam,Stewart,I,M,3.5,4,NaN,NaN,NaN,Kettering,OH,contact
10,11,adams,charles,w,M,4.0,4,3.5,3.5,NaN,Indianapolis,IN,contact
11,12,Adams,David,B,M,4.0,4,NaN,3.5,NaN,Waldron,IN,contact
12,13,Adams,Diane,NaN,F,3.5,4,NaN,4.0,NaN,Fort Collins,CO,contact
13,14,Adams,Garfield,A,M,3.5,4,4.5,4.0,NaN,Biloxi,MS,contact
14,15,Adams,John,O.,M,3.5,4,3.5,4.0,0.0,St. George,UT,contact
15,16,Adams,Jonathan,NaN,M,4.5,4,NaN,4.0,NaN,Kansas City,MO,contact
16,17,Adams,Susan,NaN,F,4.0,4,3.0,3.5,NaN,Hardeeville,SC,contact
17,18,Adams,Terry,W,M,4.5,4,NaN,4.0,0.0,Sun City,AZ,contact
18,19,Adams,Timothy,Paul,M,4.0,4,NaN,3.5,NaN,Goodyear,AZ,contact
19,20,Adkins,Will,NaN,M,3.5,4,3.5,3.5,NaN,Hillsboro,IL,contact
20,21,ADKISSON,GEOFFREY,HUNTER,M,NaN,4,3.5,NaN,NaN,Goodview,VA,contact
21,22,Agassiz,Nancy,L,F,3.5,4,NaN,3.5,0.0,Vernon,BC,contact
22,23,Aguayo,Ben,NaN,M,4.0,4,NaN,4.0,4.0,North Salt Lake,UT,contact
23,24,Aguglia,Bernard,NaN,M,4.0,4,3.5,4.0,4.0,Plattsburgh,NY,contact
24,25,Aguilar,John,Michael,M,NaN,4,NaN,3.0,NaN,Stillwater,OK,contact
25,26,Ahtye,Mitch,NaN,M,4.0,4,NaN,3.5,NaN,Castro Valley,CA,contact
26,27,Akelian,Peter,NaN,M,3.5,4,NaN,NaN,NaN,Lynn,MA,contact
27,28,Akkina,Satya Prasad,NaN,M,NaN,4,NaN,NaN,NaN,Wausau,WI,contact
28,29,Alcott,Mike,NaN,M,3.5,4,NaN,4.0,NaN,Katy,TX,contact
29,30,Alder,Gordon,NaN,M,4.0,4,NaN,4.0,NaN,Nepean,ON,contact
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3516,3517,Young,Jamaar,B,M,4.5,4,3.5,3.5,NaN,Ashland,VA,contact
3517,3518,Young,Juli,NaN,F,3.5,4,NaN,NaN,NaN,Vail,CO,contact
3518,3519,Young-Mauchly,Bobbye,NaN,F,3.0,4,NaN,3.5,NaN,Pearl City,HI,contact
3519,3520,Youngren,Beverly,J,F,4.5,4,NaN,4.5,NaN,Surprise,AZ,contact
3520,3521,Yu,Kerry,NaN,M,4.0,4,NaN,3.5,NaN,Ogden,UT,contact
3521,3522,Yunker,Brian,R,M,4.5,4,4.0,4.0,0.0,Holland,OH,contact
3522,3523,Yunker,Mike,NaN,M,4.5,4,NaN,4.0,0.0,Holland,OH,contact
3523,3524,Zalai,Marcello,NaN,M,4.5,4,3.5,4.5,0.0,Aliso Viejo,CA,contact
3524,3525,Zamora,Kim,NaN,F,4.0,4,NaN,3.5,0.0,Livonia,MI,contact
3525,3526,Zapatka,Dinah,Boyd,F,3.5,4,NaN,NaN,NaN,Savannah,GA,contact
3526,3527,Zapatka,JoAnn,M,F,4.0,4,NaN,4.0,0.0,Sun Lakes,AZ,contact
3527,3528,Zbinden,Jennifer,R.,F,NaN,4,NaN,4.0,0.0,Alta Loma,CA,contact
3528,3529,Zbinden Sr,Randy,D.,M,5.0,4,NaN,4.5,0.0,Alta Loma,CA,contact
3529,3530,Zeiger,John,NaN,M,4.5,4,NaN,3.5,NaN,Telford,PA,contact
3530,3531,Zelubowski,Paul,NaN,M,3.5,4,NaN,3.5,NaN,Edina,MN,contact
3531,3532,Zeman,Barb,D.,F,4.0,4,NaN,4.0,0.0,Sun City West,AZ,contact
3532,3533,Zepke,Gary,J,M,3.5,4,NaN,3.5,0.0,Sterling Heights,MI,contact
3533,3534,Zertuche,David,NaN,M,4.0,4,NaN,3.5,NaN,Austin,TX,contact
3534,3535,Ziebarth,Timothy,D,M,3.5,4,NaN,4.0,NaN,Granby,CO,contact
3535,3536,Ziegler,Bob,NaN,M,3.5,4,NaN,3.5,0.0,North Las Vegas,NV,contact
3536,3537,Ziervogel,Bonita,NaN,F,3.5,4,NaN,3.5,0.0,Baton Rouge,LA,contact
3537,3538,Zimmer,Robert,NaN,M,3.5,4,NaN,3.5,NaN,Ocean View,DE,contact
3538,3539,Zimmermann,Ken,W,M,4.0,4,3.0,4.0,0.0,Escondido,CA,contact
3539,3540,Zito,Kevin,L,M,5.0,4,3.5,4.5,NaN,Auburn,WA,contact
3540,3541,Zuccala,Taryn,NaN,F,4.0,4,NaN,NaN,NaN,Manchester,NH,contact
3541,3542,Zurita,Ronald,NaN,M,4.0,4,3.5,4.0,NaN,Ogden,UT,contact
3542,3543,Zwartverwer,Frederick,NaN,M,4.0,4,NaN,3.5,NaN,Klamath Falls,OR,contact
3543,3544,Zwartverwer,Merlaine,NaN,F,3.5,4,NaN,NaN,NaN,Klamath Falls,OR,contact
3544,3545,Zwilling,Jay,NaN,M,3.5,4,3.0,4.0,NaN,Olney,IL,contact
3545,3546,Zywicki,David,A,M,4.0,4,3.5,4.5,0.0,Traverse City,MI,contact